on: [workflow_dispatch, push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: Rikenunes8/infragenie-tests@feature/action
        with:
          text: "World"

      - name: Get the output
        run: echo "The greeting was ${{ steps.hello.outputs.greeting }}"
